### ISSUE TITLE
FirebaseError object endpoints[testme].availableMemoryMb failed validation

### ISSUE THREAD

**Issue by maoo** [firebase/firebase-functions#1263]
### [REQUIRED] Version info

**node:** v16.13.1

**firebase-functions:** 4.0.0-rc.0 (also reproduced with 3.24.1)

**firebase-tools:** N/A (in yarn.lock)

**firebase-admin:** 11.1.0

### [REQUIRED] Test case

```
const admin = require('firebase-admin');
const functions = require("firebase-functions");

admin.initializeApp();

exports.testme = functions.firestore.document('/users/{ts}')
    .onUpdate((snap, context) => {
        functions.logger.debug("This is a test");
});
```
### [REQUIRED] Steps to reproduce

```
firebase deploy --only functions:testme
```

### [REQUIRED] Expected behavior

The deployment completes successfully, as it always happened on this codebase for the last 6 months (and as far as I can recall, while working with Firebase Functions)

### [REQUIRED] Actual behavior

```
=== Deploying to 'fenix-app-39599'...

i  deploying functions
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  artifactregistry: ensuring required API artifactregistry.googleapis.com is enabled...
✔  artifactregistry: required API artifactregistry.googleapis.com is enabled
✔  functions: required API cloudbuild.googleapis.com is enabled
✔  functions: required API cloudfunctions.googleapis.com is enabled
i  functions: preparing codebase default for deployment
Error: Failed to parse build specification:
- FirebaseError object endpoints[testme].availableMemoryMb failed validation

Having trouble? Try firebase [command] --help
```

### Were you able to successfully deploy your functions?

See above.

**Comment by DhruvRaiPuri** [comment]
Yes, this same error has cropped up today for me as well.

**Comment by DhruvRaiPuri** [comment]
Tagging @firebase-ops

**Comment by taeold** [comment]
Taking a look @DhruvRaiPuri @maoo 

In the meantime, can you share information about the version of firebase tools used to deploy the function?

I've tried the follow, and things are unexpectedly working for me:

```
$ cat index.js
const functions = require("firebase-functions");
const { initializeApp } = require("firebase-admin/app");
const { getFirestore } = require("firebase-admin/firestore")

initializeApp()

exports.testme = functions.firestore.document('/users/{ts}')
    .onUpdate((snap, context) => {
        functions.logger.debug("This is a test");
});

$ npm ls firebase-functions
functions@ /Users/...
└── firebase-functions@4.0.0-rc.0

$ firebase --version
11.14.4

$ firebase deploy --only functions:testme
... works as before
```

**Comment by DhruvRaiPuri** [comment]
@taeold It was happening in CI environment for me. I checked and firebase version was 11.1.0. Updated it to latest 11.14.4 and the GitHub Action worked. Firebase version was already 4(release candidate).

Thanks for providing version details. From my end this issue is resolved.

**Comment by maoo** [comment]
Thank you @DhruvRaiPuri and @taeold .

I'm using firebase-tools version `11.14.0` and it's still failing for me. I'm trying to update to `11.14.4` but for some reason the command `npm install -g firebase-tools` completes successfully but `firebase --version` is still returning `11.14.0`, which is odd.

I'll keep on investigating.

**Comment by maoo** [comment]
I got it working again. These are my steps:

1. `rm -rf functions/node_modules`
2. Update `package.json` to rollback versions:

From
```
    "firebase-admin": "^11.1.0",
    "firebase-functions": "^4.0.0-rc.0"
```

To
```
    "firebase-admin": "^10.0.2",
    "firebase-functions": "^3.23.0"
```
`firebase --version` is `11.14.0` ; `node --version` is `16.14.2`.

I'm not sure what that issue really is, or where it's coming from, so I'll let you folks decide whether to close this issue or not.

Thanks for the support!

**Comment by pjarnfelt** [comment]
version 4.0.0 (not release candidate, but the final version) fixed this error for me.

**Comment by mcanyucel** [comment]
Updating version 3.23.0 to 4.0.2 also seems to cause this issue.

**Comment by JeffThurston** [comment]
Rolled back as @maoo suggests also worked for me.

**Comment by Psycarlo** [comment]
I fixed this by updating firebase tools

`npm install -g firebase-tools`

**Comment by israel-lpz** [comment]
> Solucioné esto actualizando las herramientas de Firebase
> 
> `npm install -g firebase-tools`



> Solucioné esto actualizando las herramientas de Firebase
> 
> `npm install -g firebase-tools`

Funciono para mi 👍🏻

**Comment by kolchurinvv** [comment]
Had a similar issue. Mine was due to the fact that i've just updated my Node versions to 18.x using NVM and on top of that I primarily use PNPM. my guess is that the dependencies clashed. deleting both and then installing them again starting with `npm i -g firebase-tools@latest` fixed my error

**Comment by Joebayld** [comment]
I'm having the same issue when on the latest version of everything. 

"firebase-admin": "^11.2.0",
"firebase-functions": "^4.0.1",
And Firebase CLI version 11.15.0. 

I'm receiving `- FirebaseError object endpoints[myhook].availableMemoryMb failed validation`

**Comment by conceptualben** [comment]
My 2 cents: I had the same `availableMemoryMb failed validation` error, also running from CI, and fixed it by upgrading firebase-tools:

Had errors with: `firebase-tools@11.0.1`
Fixed it with: `firebase-tools@11.10.0`

All while being on:
```
"firebase-admin": "^11.2.0",
"firebase-functions": "^4.0.1",
```

**Comment by DavidWeiss2** [comment]
> I fixed this by updating firebase tools
> 
> `npm install -g firebase-tools`

Worked for me.

**Comment by agonzalezpuerta** [comment]
> Updating version 3.23.0 to 4.0.2 also seems to cause this issue.

I am experiencing the same. Did you manage to solve this?

PD: `npm install -g firebase-tools` won't do the trick for me.

**Comment by mcanyucel** [comment]
> > Updating version 3.23.0 to 4.0.2 also seems to cause this issue.
> 
> I am experiencing the same. Did you manage to solve this? `npm install -g firebase-tools` won't do the trick for me.

No, I just downgraded to 3.23.0 for now.

**Comment by Zombobot1** [comment]
I have the same issue. Only downgrading to 3.23.0 makes everything to work again

**Comment by Psycarlo** [comment]
@radykal No need to switch to the functions folder since you are installing it globally with the flag `-g`

**Comment by anthonydzign** [comment]
I have had my firebase tools updated, I removed and reinstalled node modules(which usually works), uninstalled java and reinstalled Java 17.... and still on my Widnows PC I get the error:
`Error: Failed to parse build specification:
- FirebaseError object endpoints[sendInvitation].availableMemoryMb failed validation

My coworker has a mac and is set up the same exact way, and his works. `availableMemoryMb` is the issue. How do I fix this?

**Comment by taeold** [comment]
We are still having some trouble reproducing the issue consistently - it looks like error may be environment dependent.

We are going to start by adding more messages around the problematic code, but if someone can help us pin down the issue to particular code/environment, it would be much appreciated.

**Comment by anthonydzign** [comment]
> We are still having some trouble reproducing the issue consistently - it looks like error may be environment dependent.
> 
> We are going to start by adding more messages around the problematic code, but if someone can help us pin down the issue to particular code/environment, it would be much appreciated.

I would love to help. The problem is, my environment was working fine last week and today I can't even start the emulators.

**Comment by anthonydzign** [comment]
I wanted to post an update: This issue was with my environment variables. I went back to notes I took when I first set up my windows environment. I had to unistall Java and reinstall, change environment variables etc. Everything works now. JAVA_HOME should be %JAVA_HOME% (at least in my case). But there were extra characters after the 2nd %...(no idea how that got changed) that might have been the issue.

**Comment by Joebayld** [comment]
> We are still having some trouble reproducing the issue consistently - it looks like error may be environment dependent.
> 
> We are going to start by adding more messages around the problematic code, but if someone can help us pin down the issue to particular code/environment, it would be much appreciated.

My issues have been on a M2 Mac running macOS Ventura. I installed the latest version of firebase-tools and firebase-functions and this is still an issue.

**Comment by bartolomej** [comment]
If you installed `firebase-tools` globally, make sure to update it to the latest version with `npm update -g firebase-tools`.

This fixed the validation issues for me.

**Comment by nicholasq** [comment]
This is also an issue for me as well. I've updated firebase-tools, firebase-admin, and firebase-functions all to the latest versions. I'm using node 16 via nvm and java 17 (if that matters), on a M1 macbook.

**Comment by Hiti3** [comment]
"firebase-admin": "^11.2.1",
    "firebase-functions": "^4.1.0",
    "firebase-tools": "^11.18.0",

doesnt work, with all provided "solutions".. Where is the problem.. All i get is:

- FirebaseError object endpoints[functionXYZ].availableMemoryMb failed validation

**Comment by Hiti3** [comment]
?

**Comment by jjjeeerrr222** [comment]
```
 "dependencies": {
    "firebase-admin": "^11.4.0",
    "firebase-functions": "^4.1.1",
    "firebase-tools": "^11.18.0",
  },
  ```
  
  Also failing. Anyone got a reliable fix for this?

**Comment by clementbesson** [comment]
Hi @taeold 

Would it be possible to prioritize this issue? I can no longer deploy to firebase. I updated my machine, I updated the firebase cli to the latest version, I havent found any work around, I cannot deploy to firebase which is blocking me. I get the following error message:

`Error: Failed to parse build specification:
- FirebaseError object endpoints[trååansformStreetCleaningData].availableMemoryMb failed validation`



![Screenshot 2022-12-16 at 6 11 47 PM](https://user-images.githubusercontent.com/9371350/208218666-4121826e-d1b9-411b-9e9a-117098117af1.png)

**Comment by Saquib764** [comment]
```
 Node - 16
 "dependencies": {
    "firebase-admin": "^11.4.0",
    "firebase-functions": "^4.0.0"
    "firebase-tools": "^11.1.0",
  }
```
Same issue- `availableMemoryMb failed validation`

I tried solutions provided in previous comments. But all failed to fix the issue.

**Comment by Hiti3** [comment]
Any news here? This is rather odd..

**Comment by mellowcello77** [comment]
Still getting this, tried the above version changes and updating tools.

**Comment by asmodeoux** [comment]
For me this helped:

1. `cd functions`
2. `npm install`
3. `npm start`
4. `source ~/.zshrc`
5. `npm i -g firebase-tools`
6. `firebase deploy --only functions`

**Comment by Hiti3** [comment]
> Any news here? This is rather odd..
> 
> Still failing builds..

For all lost souls out there who don't deserve an answer..  Here is my fix at the dependency moshpit and it works!

    "firebase-admin": "^10.0.2",
    "firebase-functions": "^3.23.0",
    "firebase-tools": "^11.19.0"

Idk support, idk....

**Comment by johntdowney** [comment]
I'm pretty sure, based on the two comments above me, that this is a `firebase-tools` thing.  Make sure you update your firebase-tools... globally if you have to:

`npm i -g firebase-tools`

**Comment by Hiti3** [comment]
> > Any news here? This is rather odd..
> > Still failing builds..
> 
> For all lost souls out there who don't deserve an answer.. Here is my fix at the dependency moshpit and it works!
> 
> ```
> "firebase-admin": "^10.0.2",
> "firebase-functions": "^3.23.0",
> "firebase-tools": "^11.19.0"
> ```
> 
> Idk support, idk....

What is going on here. I just reopen the code editor try to deploy 2 days later same code...

Error: Failed to fetch Run service undefined

What is going on here?

**Comment by panieldark** [comment]
Still failing. Can we push this higher in the priority? This is quite a long list of developers

**Comment by sapar-io** [comment]
> 

I have errors when trying to npm install old versions

```
❯ npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: functions@undefined
npm ERR! Found: firebase-functions@3.24.1
npm ERR! node_modules/firebase-functions
npm ERR!   firebase-functions@"^3.23.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer firebase-functions@"^4.0.0" from firebase-functions-test@3.0.0
npm ERR! node_modules/firebase-functions-test
npm ERR!   dev firebase-functions-test@"^3.0.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

**Comment by AK-3696** [comment]
Switch to functions folder and update firebase tools with

npm install -g firebase-tools


this worked for me 👍

**Comment by mrodrig** [comment]
I was running into the `functions: Failed to load function definition from source: FirebaseError: Failed to parse build specification` error after updating to `firebase-functions` v4 as well. After making sure I had the latest Node version for the release I was using (eg. `16.19.1` at this point) and making sure I had the latest `firebase-tools` version installed, I tracked this down to an empty string being passed to the `vpcConnector` parameter for multiple functions' `runWith` configuration blocks:

```
runWith({
    timeoutSeconds: 30
    memory: '256MB',
    vpcConnector: config.vpc.name,
    vpcConnectorEgressSettings: 'ALL_TRAFFIC'
})
````

We were using an empty string for a local function emulator level config since it isn't used for local development, but that appears to have broken with `firebase-functions@4.x.x`. Changing the value to any non-empty string here resolved the issue we were running into.

Not sure if anyone else that's running into this is doing something similar, but maybe there are other values which are also causing issues for other parameters?

**Comment by sunilguptasg** [comment]
Just check the node version - using 16.x worked for me.

**Comment by samoray1998** [comment]
i have the same issue is there any work around to fix it
