### ISSUE TITLE
Firebase Parameterized configuration does not work well with Typescript

### ISSUE THREAD

**Issue by service-paradis** [firebase/firebase-functions#1342]
### Related issues

Kind of related: #5277
Related StackOverflow question: https://stackoverflow.com/q/74744707/2774496

### [REQUIRED] Version info

**node:** v18.13.0

**firebase-functions:** 4.1.1

**firebase-tools:** 11.20.0

**firebase-admin:** 11.5.0

### [REQUIRED] Test case

```js
import { Options } from '@mikro-orm/core';
import { defineString } from 'firebase-functions/params';

const config = {
  ...
  dbName: defineString('DB_NAME').value(),
  ...
} as Options;
export default config;
```

### [REQUIRED] Steps to reproduce

- Use the above code and start the emulator
- See the following warning in console:

> {"severity":"WARNING","message":"params.DB_NAME.value() invoked during function deployment, instead of during runtime."}
> {"severity":"WARNING","message":"This is usually a mistake. In configs, use Params directly without calling .value()."}
> {"severity":"WARNING","message":"example: { memory: memoryParam } not { memory: memoryParam.value() }"}

If I remove `.value` to keep `config` as:
```js
const config = {
  ...
  dbName: defineString('DB_NAME'),
  ...
} as Options;
```

I get the following Typescript error:
 > Types of property 'dbName' are incompatible.
 >    Type 'StringParam' is not comparable to type 'string'.

### [REQUIRED] Expected behavior

If using `.value()` is not supported during functions development, we should be able to use the variable without `.value()` without any errors from Typescript.

If using `.value()` is working anyway during function development, no warning should be displayed.

### [REQUIRED] Actual behavior

To be able to serve functions using Typescript, we need to use `.value()` with parameterized configurations. Unfortunately, it logs a lot of unnecessary warning to the console. But without `.value()`, we have Typescript errors preventing serving the app.

**Comment by markglibres** [comment]
I had a similar issue.. can't set environment values for deployment 

```typescript
export const test = onObjectFinalized({
  bucket: defineString('BUCKET_NAME').value(),
}, async (event) => {
  return {success: true};
});
```

**Comment by taeold** [comment]
@markglibres Can you try replacing:

```diff
export const test = onObjectFinalized({
+  bucket: defineString('BUCKET_NAME'),
-  bucket: defineString('BUCKET_NAME').value(),
}, async (event) => {
  return {success: true};
});

**Comment by taeold** [comment]
@service-paradis I think this is working as intended. The specific error message is meant to warn users precisely about wrong usage of params as seen in https://github.com/firebase/firebase-functions/issues/1342#issuecomment-1399737862.

I see that you are using params for setting options outside of Functions SDK. This is totally fine, but I think we would like to still keep the warnings. Unfortunately, I can't think of a way for our code to know whether it's being used inside a function configuration or not (without writing a special compiler that is).

As you noticed, calling `.value()` is okay.

**Comment by service-paradis** [comment]
Thank you for your response, @taeold.

Unfortunately, I still find the current situation less than ideal. If I have an environment variable that needs to be used both in a function configuration and inside a function, I am forced to use two different ways to access the value.

If I choose to use `params` for both, I receive a warning, which is not desirable. On the other hand, if I use `process.env` for both, the function configuration will be incorrect since the environment variable will be undefined at build time or during deployment.

To ensure everything works as expected, I have to use `params` for function configuration and `process.env` inside the function to access the same variable. This can be quite confusing to me and adds unnecessary complexity.

Do you have any suggestions for how we could simplify this process and avoid the need for multiple methods of accessing environment variables?

**Comment by service-paradis** [comment]
> @markglibres Can you try replacing:
> 
> ```diff
> export const test = onObjectFinalized({
> +  bucket: defineString('BUCKET_NAME'),
> -  bucket: defineString('BUCKET_NAME').value(),
> }, async (event) => {
>   return {success: true};
> });
> ```

@taeold Your suggestion does not work unfortunately. It looks like we cannot use Parameterized configuration for bucket name right now. If we use your suggestion, Typescript is complaining with the following error:
> Type 'StringParam' is not assignable to type 'string'.ts(2769)
storage.d.ts(162, 5): The expected type comes from property 'bucket' which is declared here on type 'StorageOptions'

If we use `defineString('BUCKET_NAME') as any` to remove the error and we try to build the app, we get the following error in console:
> !!  functions: Failed to load function definition from source: FirebaseError: Failed to load function definition from source: Failed to generate manifest from function source: Error: 
Invalid bucket name params.BUCKET_NAME

**Comment by markglibres** [comment]
> @markglibres Can you try replacing:
> 
> ```diff
> export const test = onObjectFinalized({
> +  bucket: defineString('BUCKET_NAME'),
> -  bucket: defineString('BUCKET_NAME').value(),
> }, async (event) => {
>   return {success: true};
> });
> ```

@taeold  it didn't worked with the latest version of firebase...  any ideas how to make this work with storage?

**Comment by tuclicks** [comment]
I have same thing.

**Comment by ktpeace** [comment]
For me it is still throwing this error when `.value()` is used in config -- but everything works in deployment anyway.

**Comment by juanzero000** [comment]
I have a similar issue, I'm trying to specify a bucket for a cloud function, but the value is not available on deployment if I use it like this:
```
const bucketName = defineString("BUCKET_NAME").value();

export default onObjectFinalized(
  {
    bucket: bucketName, // I get the "...invoked during function deployment, instead of during runtime." warning
  },
...
```

I've also tried these alternatives:
```
export default onObjectFinalized(
  {
    bucket: defineString("BUCKET_NAME").value() // same warning on the console and the value is undefined on deployment
  },
...
```

```
export default onObjectFinalized(
  {
    bucket: defineString("BUCKET_NAME") as any // Invalid bucket name error is thrown
  },
...
```

How is the correct way to use the env variables for deployment on typescript?

**Comment by inlined** [comment]
Ran into this old issue as it was referenced in a fresh one and wanted to ping with a couple of updates:

1. Buckets can now be parameterized. Consider also that we have a params.BUCKET_PICKER_INPUT you can pass as the `input` option to your params definition and the CLI will display a selection of actual buckets in your project!
2. Firestore selectors will be parameterizable in this week's release
3. We've released but not finished documenting the `onInit` lifecycle hook. With this you have a safe place to initialize your global vars before function exeuction without choking because the value was read on your local machine during deploy

**Comment by johnnyoshika** [comment]
@inlined Sounds promising. Which release will reflect these changes?

**Comment by kcrebound** [comment]
> @inlined Sounds promising. Which release will reflect these changes?

try to update `firebase-functions` package, helped to me

**Comment by inlined** [comment]
It's all released. Just update to latest

**Comment by nickjuntilla** [comment]
@taeold Do onInit values still get added to the runtime? I'm not sure I understand this function. So if I do this:

let client;
onInit(() => {
  client = require('twilio')(params.TWILIOID.value(), params.TWILIOTOKEN.value());
});

Will client be initialized during runtime or just during deployment? Or is it initialized for deployment and not for runtime?
