### ISSUE TITLE
Storage onFinalize trigger not working in Node 10 runtime

### ISSUE THREAD

**Issue by loicmarie** [firebase/firebase-functions#456]
### Related issues

No related issue

### [REQUIRED] Version info

**node:** 10.15.3

**firebase-functions:** ^2.3.0

**firebase-tools:** 6.10.0

**firebase-admin:** ~7.0.0

### [REQUIRED] Test case

Following the [official example](https://firebase.google.com/docs/functions/gcp-storage-events#trigger_a_function_on_changes) :
```
exports.generateThumbnail = functions.storage.object().onFinalize(async (object) => {
  console.log(object);
});
```

### [REQUIRED] Steps to reproduce

When setting node runtime in `package.json` in `functions` directory :
```
{
  ...
  "engines": {
    "node": "10"
  }
}
```
### [REQUIRED] Expected behavior

Should output `ObjectMetadata` content in function logs, whatever the node runtime is.

### [REQUIRED] Actual behavior

Output is 'undefined' with node 10 runtime, **but is working fine with node 8 runtime** (can see the `ObjectMetadata` properties outputted)

### Were you able to successfully deploy your functions?

`firebase deploy` runs successfully, but `object` is undefined.

**Comment by thechenky** [comment]
Hi @loicmarie this is likely the same issue as https://github.com/firebase/firebase-functions/issues/447. Can you post the error you're seeing when your function runs?

**Comment by loicmarie** [comment]
Hi @thechenky, I have no error, since I am not doing anything ATM, but the problem is that object variable should not be undefined, it should be an instance of ObjectMetadata.
It works with Node 8 and Node 10 with local emulator, but not online with Node 10.

**Comment by thechenky** [comment]
Hm, this looks like it may be caused by a missing `FIREBASE_CONFIG` env var. We had some issues on the backend that were fixed recently, but the changes would require a redeploy to take effect. Can you redeploy and see if this is still occurring?

If it is still occurring even after redeploy, check whether the `FIREBASE_CONFIG` var is set by printing the following and pasting in your response:

```
console.log(process.env.FIREBASE_CONFIG)
```

This env var will not be set if you're deploying with another tool, so please use the Firebase CLI if you're not already.

**Comment by loicmarie** [comment]
It is still occuring after redeploy, and the outputted `FIREBASE_CONFIG` variable seems correct to me in console logs. For this cloud function with Node 10 :
```
export const generateThumbs = functions.storage
  .object()
  .onFinalize(async (object) => {
    console.log(process.env.FIREBASE_CONFIG);
    console.log('object', JSON.stringify(object));
  })
```

Here are the logs (hiding my project ID):

```
10:01:49.394 PM |   | generateThumbs
{
  "projectId": "<my_project_id>",
  "databaseURL":"https://<my_project_id>.firebaseio.com",
  "storageBucket":"<my_project_id>.appspot.com",
  "cloudResourceLocation":"europe-west"
}

10:01:49.397 PM |   | generateThumbs | object undefined
```
I am deploying with `firebase deploy` using the SDK.

**Comment by thechenky** [comment]
Thanks for the the quick response and helping me rule out the other possible issues. I think I know what's happening here. As a quick sanity check, would you mind setting another env var in your function and see whether that fixes the object being undefined? In the global scope of your function: 

```
process.env.X_GOOGLE_NEW_FUNCTION_SIGNATURE = true;
```

Followed by a redeploy. Super appreciate your help in tracking down this issue!

**Comment by loicmarie** [comment]
Works like a charm now !

```
10:01:49.394 PM |   | generateThumbs
{
  "projectId": "<my_project_id>",
  "databaseURL":"https://<my_project_id>.firebaseio.com",
  "storageBucket":"<my_project_id>.appspot.com",
  "cloudResourceLocation":"europe-west"
}
11:45:26.932 PM |   | generateThumbs | object
{
   "bucket":"<my_project_id>.appspot.com",
   "contentDisposition":"inline; filename*=utf-8''image.jpg",
   "contentType":"image/jpeg",
   "crc32c":"WCmI3w==",
   "etag":"CMPmz8GkzuICEAE=",
   "generation":"1559598325822275",
   "id":"<my_project_id>.appspot.com/users/xb1PUonyilfyq3MQMkKh1V2PmHY2/cover/image.jpg/1559598325822275",
   "kind":"storage#object",
   "md5Hash":"lzoTbb/SNAH6XahgYMkuQg==",
   "mediaLink":"https://www.googleapis.com/download/storage/v1/b/<my_project_id>.appspot.com/o/users%2Fxb1PUonyilfyq3MQMkKh1V2PmHY2%2Fcover%2Fimage.jpg?generation=1559598325822275&alt=media",
   "metadata":{
      "firebaseStorageDownloadTokens":"<token>"
   },
   "metageneration":"1",
   "name":"users/xb1PUonyilfyq3MQMkKh1V2PmHY2/cover/image.jpg",
   "selfLink":"https://www.googleapis.com/storage/v1/b/<my_project_id>.appspot.com/o/users%2Fxb1PUonyilfyq3MQMkKh1V2PmHY2%2Fcover%2Fimage.jpg",
   "size":"163562",
   "storageClass":"STANDARD",
   "timeCreated":"2019-06-03T21:45:25.821Z",
   "timeStorageClassUpdated":"2019-06-03T21:45:25.821Z",
   "updated":"2019-06-03T21:45:25.821Z"
}
```
It's I who should be thanking you. That was efficient ! I think it closes my issue.

**Comment by thechenky** [comment]
@loicmarie just to clarify - did it work after you set the `X_GOOGLE_NEW_FUNCTION_SIGNATURE` env var? If so, this is still a bug on our side :) one that has been reported previously in https://github.com/firebase/firebase-functions/issues/447.

**Comment by loicmarie** [comment]
Yes it worked after I set : 
`process.env.X_GOOGLE_NEW_FUNCTION_SIGNATURE = 'true';`
as first line of my index.ts (couldn't pass tsc validator without setting a string).

As this is still in beta, I thought I missed something in the doc. Should I reopen and close at fix release ?

**Comment by thechenky** [comment]
Thanks for clarifying! Yes, this is still a bug, you shouldn't need to set that variable. I was trying to understand whether this was the issue I thought it was, and you have confirmed it, so thank you! We can keep this closed for the reason that it is a duplicate of https://github.com/firebase/firebase-functions/issues/447. But please follow the original issue for the resolution. Thanks again!

**Comment by thechenky** [comment]
Duplicate of https://github.com/firebase/firebase-functions/issues/447

**Comment by nehawankar174** [comment]
How can I get or fetch "User Id" and "File Name" from the following response- 

| generateThumbs | object
{
   "bucket":"<my_project_id>.appspot.com",
   "contentDisposition":"inline; filename*=utf-8''image.jpg",
   "contentType":"image/jpeg",
   "crc32c":"WCmI3w==",
   "etag":"CMPmz8GkzuICEAE=",
   "generation":"1559598325822275",
   "id":"<my_project_id>.appspot.com/users/xb1PUonyilfyq3MQMkKh1V2PmHY2/cover/image.jpg/1559598325822275",
   "kind":"storage#object",
   "md5Hash":"lzoTbb/SNAH6XahgYMkuQg==",
   "mediaLink":"https://www.googleapis.com/download/storage/v1/b/<my_project_id>.appspot.com/o/users%2Fxb1PUonyilfyq3MQMkKh1V2PmHY2%2Fcover%2Fimage.jpg?generation=1559598325822275&alt=media",
   "metadata":{
      "firebaseStorageDownloadTokens":"<token>"
   },
   "metageneration":"1",
   "name":"users/xb1PUonyilfyq3MQMkKh1V2PmHY2/cover/image.jpg",
   "selfLink":"https://www.googleapis.com/storage/v1/b/<my_project_id>.appspot.com/o/users%2Fxb1PUonyilfyq3MQMkKh1V2PmHY2%2Fcover%2Fimage.jpg",
   "size":"163562",
   "storageClass":"STANDARD",
   "timeCreated":"2019-06-03T21:45:25.821Z",
   "timeStorageClassUpdated":"2019-06-03T21:45:25.821Z",
   "updated":"2019-06-03T21:45:25.821Z"
}

Thanks!

**Comment by lunedam-git** [comment]
It's now late May and I find that I still have to set process.env.X_GOOGLE_NEW_FUNCTION_SIGNATURE = 'true'; in order for my functions to work in Node 10 (which is still it seems only in beta despite the mail bombing from Google about updating). Surely this should be resolved by now?

**Comment by CyrusZei** [comment]
After a couple of hours, this looks like I also have the same thing here. The output is undefined when I do
 `functions.storage.object().onFinalize(object => { console.log('object',object) })`

**Comment by liezl200** [comment]
Setting `process.env.X_GOOGLE_NEW_FUNCTION_SIGNATURE = 'true'; `in my index.js is not working. I also tried `process.env.X_GOOGLE_NEW_FUNCTION_SIGNATURE = true;`
  I still get "TypeError: functions.storage.bucket(...).onFinalize is not a function"

**Comment by lunedam-git** [comment]
Hey @liezl200 , I don't think your error has anything to do with the NEW_FUNCTION signature. Looks like it's a Typescript warning that there's something wrong with your code.

Try "functions.storage.object().onFinalize..." if you're listening for changes on the default bucket or "functions.storage.bucket('MYBUCKET').object().onFinalize..." if you're listening for changes on a bucket called 'MYBUCKET'.

See the docs at [https://firebase.google.com/docs/functions/gcp-storage-events](https://firebase.google.com/docs/functions/gcp-storage-events)
