### ISSUE TITLE
Warning, estimating Firebase Config based on GCLOUD_PROJECT. Initializing firebase-admin may fail

### ISSUE THREAD

**Issue by skhaz** [firebase/firebase-functions#853]
### [REQUIRED] Version info

**node:** v12.20.0

**firebase-functions:** 3.11.0

**firebase-tools:** 9.2.2

**firebase-functions-test:** 0.2.3

**firebase-admin:** 9.2.0

### [REQUIRED] Test case

Just create a unit-test with jest and run `firebase emulators:exec --only firestore --project sample 'jest'`

### [REQUIRED] Expected behavior

No warnings shown

### [REQUIRED] Actual behavior

A warning

> {"severity":"WARNING","message":"Warning, estimating Firebase Config based on GCLOUD_PROJECT. Initializing firebase-admin may fail"}

### Were you able to successfully deploy your functions?

Yes

**Comment by syslogic** [comment]
Issue #630 might explain the background.

**Comment by samtstern** [comment]
This seems like a duplicate of https://github.com/firebase/firebase-tools/issues/3086 and this is definitely not an issue with `firebase-functions`.  If there is a bug here it would be in the Firebase CLI or the Firebase Admin SDK.  So if you can explain more about this bug let's go back to the original issue.

**Comment by skhaz** [comment]
@samtstern that's why everbody prefers AWS.

Instead of helping me, you guys "threw" me again to another project.

**Comment by skhaz** [comment]
This warning should be fixed.

The warning appears on every set of tests of my project, it's very annoying

**Comment by samtstern** [comment]
@skhaz we manage to help many people on GitHub every day but you have to work with us. I did not push you to another repo, I asked you for more information to prove that you were in the right place and instead you closed the issue and repeated the same mistake here.

Help us identify an actual bug and then we will work to identify and fix it.  Instead you repeatedly refused to provide more information and decided instead to attempt to shame us into fixing the issue with your opinions about AWS.  That's not a respectful way to interact online and not a successful strategy to get attention or help.

That warning exists in the SDK to let you know when things are misconfigured. It does *not* show up every time for every user, it seems to show up every time for you.  So either:

1. We have a bug in our SDK
2. There's something misconfigured in your environment

It's totally possible that the situation is (1) but if you don't provide all the evidence we need we have to assume it is (2).

**Comment by rcknr** [comment]
@samtstern This issue refers to this line: https://github.com/firebase/firebase-functions/blob/2e718c74a382655a9756c0ff781278c0e8a9146b/src/setup.ts#L50
So @skhaz is right by filing it in this repository.
Initializing Firebase using `GCLOUD_PROJECT` is often used and should not create a warning.

**Comment by rcknr** [comment]
@samtstern Thanks for clarifying the details I wasn't aware of! Consider though that we are talking about zero configuration here, which could assume sensible defaults. Carrying on with your example, I could customize `DATABASE_URL` (or `STORAGE_BUCKET_URL`) environment variable and still get the warning.
Many people would avoid using JSON in environmental variables as it needs to be parsed before which is an extra point of failure. I would be so sure about the warning being correct in this case.

**Comment by samtstern** [comment]
@rcknr that's fair but `FIREBASE_CONFIG` is not something we expect you to provide yourself. It's provided as part of the Cloud Functions environment we set up on deploy with the Firebase CLI. So in the event that you're running this library (firebase-functions) and not in that environment (or in our emulator, where it's also provided) it's appropriate that we warn you as you're in uncharted waters.

**Comment by rcknr** [comment]
@samtstern Is `FIREBASE_CONFIG` also set when deploying cloud functions with `gcloud`?

**Comment by samtstern** [comment]
@rcknr no I don't believe it is ... however I think you first deploy with `firebase` and later with `gcloud` it would be preserved.

**Comment by aabccd021** [comment]
I don't know whether this is relevant, but I've found that the warning was given when importing `firebase-functions`, so I was able to solve the warning by importing it after the app is initialized.

Before:
```ts
import * as admin from 'firebase-admin';
import * as functions from 'firebase-functions';
admin.initializeApp({ projectId: 'demo-foo' });
```

After:
```ts
import * as admin from 'firebase-admin';
admin.initializeApp({ projectId: 'demo-foo' });
import * as functions from 'firebase-functions';
```

**Comment by phcoliveira** [comment]
I wish this was reopened because, IMHO, we are missing the point here. In my case, I am not only using the environment variable `GCLOUD_PROJECT`. I am also using  the ones due to the emulator: `FIREBASE_DATABASE_EMULATOR_HOST` and `FIREBASE_AUTH_EMULATOR_HOST`. These variables end up replacing the original configuration. That's why I think this (annoying) warning is not due when Firebase is connected to the emulator.
